### PR TITLE
Service structure and Swagger

### PR DESCRIPTION
**Pull request by JabX**
This PR adds the basic structure for the API and some Swagger-goodness.

There's a lot of content because I dumped the Swagger-UI app in there because we need to serve it to browse the API. (only the last 6 files here are ours).

There's a `./services` folder in which our services will be placed. They need to be written as a function that takes the express app as a parameter, and then imported and called in the index file.

As for Swagger, the standard tool to build Swagger APIs (`swagger-node`) is *very* opinionated and wants to take over your project by replacing the entire development workflow, so I chose not to use it. Instead, I found a smaller tool called `swagger-jsdoc` that lets us write the Swagger definitions as JSDoc directly in our files ([see here for an example](http://mherman.org/blog/2016/05/26/swagger-and-nodejs)), which is way lighter. There's a bit of redundancies with Typescript but there's no magic  tool (yet) that will do better.

It's all configured in the `swagger/` directory, and what it does is that it generates the `swagger.json` file on startup and serves it on the `/swagger.json` route.

Then, using Swagger-Ui which is currently served on the root of the server, you can query the api and it works great. We might have to reconsider its placement since we might serve the back-office app here instead.

### CODE REVIEW

**Comment by pierr** [comment]
@JabX it seems you added swagger generated files maybe they should be in the .gitignore

**Comment by JabX** [comment]
There isn't any generated file by Swagger, just the swagger-ui client, which I mentioned here:

> There's a lot of content because I dumped the Swagger-UI app in there because we need to serve it to browse the API.

**Comment by pierr** [comment]
@JabX ok but could this be in the gitignore and add via npm install?

**Comment by JabX** [comment]
Maybe we could do something like cloning the git repo on postinstall indeed, I'll look into this.

**Pull request merged**
